services:
  postgres:
    image: postgres:15-alpine
    container_name: hrs_postgres
    environment:
      POSTGRES_DB: HRS
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d HRS"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

  backend:
    image: hr-management-backend:v1.0   #for changing image version backend
    build:
      context: .
      dockerfile: dockerfile
    container_name: hrs_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/HRS
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 5
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 2
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    image: hr-management-frontend:v1.0  #for changing image version frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hrs_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://postgres:8081/api
    depends_on:
      - backend
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  postgres_data: