spring.application.name=spring-boot-database-integration

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/HR management System
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#server configuration
server.port=8081